# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Julien Beaulieu
tagline:             'Data Scientist'
description:         'I am Julien Beaulieu, and I work as a data scientist. I write about Data Science, learning and productivity. Contact me to have a chat.'
url:                 https://julienbeaulieu.github.io
baseurl:             'https://julienbeaulieu.github.io'
paginate:            5

# About/contact
author:
  name:              Julien Beaulieu
  url:               https://www.linkedin.com/in/julienbeaulieu/
  email:             beaulieu.jb@gmail.com

# Custom vars
version:             1.0.0
