# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Julien Beaulieu
tagline:             'Aspiring Data Scientist'
description:         'I am Julien Beaulieu, an aspiring data scientist. Sometimes I like to write. Contact me to have a chat'
url:                 https://julienbeaulieu.github.io
baseurl:             'julienbeaulieu.github.io'
paginate:            5

# About/contact
author:
  name:              Julien Beaulieu
  url:               https://twitter.com/mdo
  email:             beaulieu.jb@gmail.com

# Custom vars
version:             1.0.0
